### ISSUE TITLE
Problem: lost utxo in client-rpc

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1005] opened 2020-02-05 14:29 UTC
1) create wallet a
2) create wallet b
3) unbond 20000000000000   carson unit in wallet a
4) withdraw from wallet a to wallet a transfer address with wallet a viewkey
5) sync wallet a
6) unbond is 0 , that's ok
7) but amount is lost after sync
8) tried from genesis, utxo is lost
in client-cli, it's working fine

**Comment by tomtau** [comment] 2020-02-06 01:01
@leejw51crypto isn't this related to "pending" -- so if you ran the sync again after longer time, it's fine?

**Comment by yihuang** [comment] 2020-02-06 06:00
I tried `client-rpc` with withfee env, seems fine here:
```
$ chainrpc.py staking state 0x33502ed39d0c4e2044fb37fdcd5161493f5900c3
address:       0x33502ed39d0c4e2044fb37fdcd5161493f5900c3
bonded:        0
council_node:  null
nonce:         0
punishment:    null
unbonded:      500000000000000000
unbonded_from: 1574240208
$ chainrpc.py address list --type transfer
dcro1qf26s0auk6p68snflspan44hm4f8gvjw56yh8ju95yh49edrjzxq2swuys
dcro1mq6d4n9nmp90lmxkvpgznc0l6kkru8u63qqu2ysmz8lalqf3c4ms8zxrup
$ chainrpc.py staking withdraw_all_unbonded 0x33502ed39d0c4e2044fb37fdcd5161493f5900c3 dcro1qf26s0auk6p68snflspan44hm4f8gvjw56yh8ju95yh49edrjzxq2swuys
c1dd8fa9027104aa15467f20406302ee98666a98c81d62522d98bc41586e1e3d
$ chainrpc.py wallet sync
$ chainrpc.py wallet balance
available: 499999999999999703
pending:   0
total:     499999999999999703
$ chainrpc.py staking state 0x33502ed39d0c4e2044fb37fdcd5161493f5900c3
address:       0x33502ed39d0c4e2044fb37fdcd5161493f5900c3
bonded:        0
council_node:  null
nonce:         1
punishment:    null
unbonded:      0
unbonded_from: 1574240208
```

**Comment by yihuang** [comment] 2020-02-20 02:26
With withfee env, when supply viewkey when withdraw, issue #1101 happens.
With zerofee env, no problem.
Is it a duplicate of #1101, @leejw51crypto ?

**Comment by leejw51crypto** [comment] 2020-02-20 02:49
for zero fee, in client-rpc,
i couldn't proceed,
only client-cli successful
i'll check again

**Comment by tomtau** [comment] 2020-02-24 14:40
it seems it's not possible to reproduce -- @leejw51crypto feel free to reopen if it's still relevant

**Closed by tomtau** 2020-02-24 14:40 UTC
