### ISSUE TITLE
Problem: Dockerfile is missing for chain-tx-enclave

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#1135] opened 2020-02-26 03:20 UTC
Was trying to follow guide here 
https://github.com/crypto-com/chain/tree/master/chain-tx-enclave#build-the-docker-image
to build a mock enclave, but the Dockerfile pointed to in the command below is missing

```
$ docker build -t chain-tx-validation \
-f ./tx-validation/Dockerfile . \
--build-arg SGX_MODE=SW \
--build-arg NETWORK_ID=AB
```

**Comment by yihuang** [comment] 2020-02-26 03:28
`docker build -t crypto-chain -f docker/Dockerfile.new --build-arg SGX_MODE=SW`
You should use this now, the `README` needs to be changed.

**Comment by CeruleanAtMonaco** [comment] 2020-02-26 08:14
> `docker build -t crypto-chain -f docker/Dockerfile.new --build-arg SGX_MODE=SW`
> The resulting image contains all the binaries including enclaves.
> The `README` needs to be changed.

super useful!

**Comment by tomtau** [comment] 2020-02-26 08:16
a duplicate of https://github.com/crypto-com/chain/issues/818 ?

**Comment by yihuang** [comment] 2020-02-26 08:31
> a duplicate of #818 ?

Yeah, we can do the README fixes at once.

**Closed** 2020-02-26 09:58 UTC
