### ISSUE TITLE
(CRO-340) Problem: No details for new staking address in query response

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#750] opened 2019-12-29 11:40 UTC
RPC Error is returned from Tendermint RPC `chain_abci(account)` call without further details

**Comment by tomtau** [comment] 2020-01-08 07:11
Is this a duplicate of https://github.com/crypto-com/chain/issues/838 ?

**Comment by tomtau** [comment] 2020-02-25 07:00
seems a duplicate

**Closed by tomtau** 2020-02-25 07:00 UTC
Labels: Staking
