### ISSUE TITLE
(CRO-645) Problem: no stress test for chain

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#772] opened 2019-12-29 12:44 UTC
write python script, which does some stress test to make bad txs
consider it as a part of integration test

1. very abnormal txs
2. very big amount of txs 

check that chain doesn't crash, and bloom-filter works well.

**Comment by tomtau** [comment] 2019-12-31 06:13
possible duplicate of CRO-551 and CRO-32

**Closed** 2020-01-02 01:08 UTC
