### ISSUE TITLE
Problem: client db slow with massive input

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1250] opened 2020-03-16 15:29 UTC
1. check with sled for performance,
- check db size
- and speed per request
- speed for transaction (or write-batch)

2. add write batch to storage and storage implementation

it will bring at least 3 or 4 times performance enhancement if we use write batch in embedded db , 
especially, it's better to make write batch per block commit

benefits will be like below
1. robust block commit
2. increased throughput
3. stable, because whole write batch is also a transaction

**Comment by tomtau** [comment] 2020-03-17 01:27
duplicate of https://github.com/crypto-com/chain/issues/1233

**Closed by tomtau** 2020-03-17 01:27 UTC
