### ISSUE TITLE
(CRO-239) client index stress test

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-com/chain#765] opened 2019-12-29 12:17 UTC
make stress test  for merchant such as exchange

make many wallets (thousands)
also many utxos (thousands )
write harsh test aging

make sure that client index sync correctly 
also make sure that abci server works correctly

**Comment by tomtau** [comment] 2019-12-31 06:08
duplicate of CRO-551

**Closed by tomtau** 2019-12-31 06:08 UTC
Labels: Escrow
