### ISSUE TITLE
Problem: python integration tests not executed in CI

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#912] opened 2020-01-16 03:57 UTC
The tests in `integration-tests/bot/tests`.
It should be trivial to do now with the new environment setup script.

**Comment by tomtau** [comment] 2020-01-16 04:16
Is this a duplicate of https://github.com/crypto-com/chain/issues/853 ?

**Comment by yihuang** [comment] 2020-01-16 04:32
> Is this a duplicate of #853 ?

I was intent to make a smaller one first to add the existing tests in directory `integration-tests/bot/tests`.

**Comment by yihuang** [comment] 2020-01-16 04:46
Got a block with this one, currently, it's unable to restore a wallet with the same private key as an existing one. And there is not delete wallet API.

**Comment by tomtau** [comment] 2020-01-16 05:15
> > Is this a duplicate of #853 ?
> 
> I was intent to make a smaller one first to add the existing tests in directory `integration-tests/bot/tests`.

ok

> Got a block with this one, currently, it's unable to restore a wallet with the same private key as an existing one (is this considered a bug?). And there is not delete wallet API, so no way to work around it in test case.

https://github.com/crypto-com/chain/issues/914
https://github.com/crypto-com/chain/issues/915

**Closed** 2020-01-20 01:41 UTC
