### ISSUE TITLE
Problem: too much db space for a new transfer address

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1257] opened 2020-03-17 03:07 UTC
for current benchmark)
216,000,000 bytes 1800 addresses
1 address = 120,000 bytes

1 tx address consumes 120,000 bytes,
on usual case, it's ok.

but in massive stress test, it's too much.

**Comment by tomtau** [comment] 2020-03-25 10:21
duplicate of https://github.com/crypto-com/chain/issues/1233

**Closed by tomtau** 2020-03-25 10:21 UTC
