### ISSUE TITLE
Problem: no detail information of light client error

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#2022] opened 2020-07-26 12:40 UTC
display exact error message which failed in `light client` calls.
if possible, display `how to fix that error` , too.

**Comment by tomtau** [comment] 2020-07-27 00:57
duplicate of https://github.com/crypto-com/chain/issues/2006
-- will be resolved with a new tendermint-rs release

**Closed by tomtau** 2020-07-27 00:57 UTC
