### ISSUE TITLE
Problem: no separation of wallet and sync storage

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1021] opened 2020-02-08 05:18 UTC
if we store only wallet information as separate folder, backup will be easier
.wallet-storage <- only for wallet
.sync-storage <- only for sync
.cro-storage <- chain core

**Comment by yihuang** [comment] 2020-02-08 15:19
Kind of duplicate of #827? As long as we can backup wallet, no need to separate storage?

**Comment by tomtau** [comment] 2020-02-10 01:36
yeah, looks like a duplicate

**Closed by tomtau** 2020-02-10 01:36 UTC
