### ISSUE TITLE
Problem: Not able to do sanity check on max coin supply in chain-abci

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain#1327] opened 2020-03-31 00:40 UTC
Because the content of UTxO is obfuscated.
Potential solutions:
- Tracking the total amount of UTxO set, because UTxO operations are relatively simpler, we can trust the UTxO tracking won't go wrong.
- Not obfuscate amount field in UTxO.

**Comment by tomtau** [comment] 2020-03-31 01:19
duplicate of https://github.com/crypto-com/chain/issues/1038

"Tracking the total amount of UTxO set" is the only option, as the latter solution defeats the purpose of obfuscation

**Closed by tomtau** 2020-03-31 01:19 UTC
