### ISSUE TITLE
Problem: incorrect fee estimation

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1001] opened 2020-02-05 12:58 UTC
with this config
"initial_fee_policy": {
        "base_fee": "1.1",
        "per_byte_fee": "1.25"
    },
"withdrawal from unbonded" doesn't working
1) don't use mocking, use tx-query directly to get encryption size
or
2) use some deterministic method not using tx-query

**Comment by tomtau** [comment] 2020-02-06 00:49
@leejw51crypto no. 2 solution.

can you post steps to reproduce? that configuration you posted is the same as https://github.com/crypto-com/chain/blob/master/integration-tests/with_fee_cluster.json#L21 and the existing tests (should) execute withdrawal and seem to succeed

**Comment by tomtau** [comment] 2020-02-06 09:49
to-be-confirmed: it may be due to this "hack" https://github.com/crypto-com/chain/blob/master/chain-tx-enclave/tx-validation/app/src/server/mod.rs#L172


should disappear after this is resolved: https://github.com/crypto-com/chain/issues/866

**Comment by tomtau** [comment] 2020-02-24 14:41
possibly fixed with https://github.com/crypto-com/chain/pull/1118

**Closed by tomtau** 2020-02-24 14:41 UTC
