### ISSUE TITLE
Problem: outdated build pre-requisites in README

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1076] opened 2020-02-14 11:49 UTC
1. add one-line install commands
- apt install ...

2. add "clang" to pre-requisites

3. verify with ubuntu 18 installation, so that user can compile easily

**Comment by tomtau** [comment] 2020-02-27 02:20
duplicate of https://github.com/crypto-com/chain/issues/818

**Closed by tomtau** 2020-02-27 02:20 UTC
